In [32]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
df=sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [35]:
from sklearn.model_selection import train_test_split

X= df.drop('species',axis= 1)
y= df['species']

In [36]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [37]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)

In [38]:
knn_model.fit(X_train,Y_train)

KNeighborsClassifier()

In [39]:
knn_model.score(X_test,Y_test)

0.98

In [40]:
from sklearn.svm import SVC

model_svc = SVC(gamma='auto')

In [41]:
model_svc.fit(X_train,Y_train)

SVC(gamma='auto')

In [42]:
model_svc.score(X_test,Y_test)

1.0

In [43]:
#now lets use the grid search CV

In [44]:
from sklearn.model_selection import GridSearchCV

In [45]:
classifier = GridSearchCV((model_svc),{
  'C':[1,10,20,30],
  'kernel' :['rbf','linear']
},cv=5,return_train_score=False)

In [46]:
classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [47]:
classifier.cv_results_

{'mean_fit_time': array([0.00378242, 0.00272484, 0.00240254, 0.00229754, 0.00225191,
        0.00282331, 0.00254307, 0.00263195]),
 'std_fit_time': array([0.00168119, 0.00080932, 0.00021699, 0.00027604, 0.00010904,
        0.00045256, 0.00025621, 0.00061447]),
 'mean_score_time': array([0.00261564, 0.00166287, 0.00184283, 0.00178142, 0.00185294,
        0.00192294, 0.0021636 , 0.00211902]),
 'std_score_time': array([7.64769808e-04, 1.21559120e-04, 2.18213761e-04, 3.98518349e-05,
        3.20331324e-04, 2.30765273e-04, 3.44507518e-04, 5.04419194e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [48]:
res=pd.DataFrame(classifier.cv_results_)

In [49]:
res.head(8)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003782,0.001681,0.002616,0.000765,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.002725,0.000809,0.001663,0.000122,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.002403,0.000217,0.001843,0.000218,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.002298,0.000276,0.001781,0.000040,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.002252,0.000109,0.001853,0.000320,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.002823,0.000453,0.001923,0.000231,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.002543,0.000256,0.002164,0.000345,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.002632,0.000614,0.002119,0.000504,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [50]:
res[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [51]:
from sklearn.neighbors import KNeighborsClassifier

model_knn = KNeighborsClassifier()

In [52]:
knn_classifer = GridSearchCV(model_knn,
{
  'n_neighbors': [3,5,7,9,11,13],
  'weights':['uniform','distance'],
  'metric':['euclidean','manhattan']
  },cv=5,return_train_score=False
)

In [53]:
knn_classifer.fit(X,y)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'metric': ['euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11, 13],
                         'weights': ['uniform', 'distance']})

In [54]:
knn_classifer.cv_results_

{'mean_fit_time': array([0.00668716, 0.00414085, 0.00271039, 0.00496898, 0.00267863,
        0.00231171, 0.00217352, 0.00200577, 0.00204654, 0.00278683,
        0.00235009, 0.00194855, 0.00241976, 0.0030467 , 0.00255399,
        0.00219069, 0.00602145, 0.00288453, 0.00264196, 0.00200739,
        0.00224571, 0.00279393, 0.00202694, 0.00184865]),
 'std_fit_time': array([1.87301775e-03, 8.10298223e-04, 6.79219599e-04, 1.87392726e-03,
        8.13798533e-04, 3.39885700e-04, 1.90627103e-04, 2.10790039e-04,
        3.26417218e-04, 1.28174268e-03, 7.37290604e-04, 9.88051467e-05,
        2.64468151e-04, 9.79196470e-04, 1.16895937e-03, 3.35546097e-04,
        1.82417204e-03, 4.38799471e-04, 5.61753160e-04, 1.71002780e-04,
        2.65765198e-04, 9.36468720e-04, 1.26679274e-04, 4.04532188e-05]),
 'mean_score_time': array([0.01430411, 0.00815244, 0.00537457, 0.00692449, 0.00404983,
        0.00269165, 0.00414872, 0.00375223, 0.00384417, 0.00240202,
        0.0033803 , 0.00299377, 0.00415378, 0.00245991, 0.00347762,
        0.0030169 , 0.00552049, 0.00507469, 0.00372419, 0.0024868 ,
        0.00373049, 0.00246687, 0.00385056, 0.00259295]),
 'std_score_time': array([8.52437205e-03, 6.13645782e-03, 1.77912371e-03, 3.73255721e-03,
        1.29403885e-03, 3.14438426e-04, 1.48973849e-03, 2.06305851e-03,
        9.47573779e-04, 2.80463253e-04, 6.31829333e-04, 9.04130097e-04,
        1.16582919e-03, 2.65720030e-04, 1.09645502e-03, 1.53436605e-03,
        1.83351821e-03, 1.60349374e-03, 1.25771916e-03, 6.35672966e-04,
        9.44677923e-04, 5.17196671e-05, 9.84538114e-04, 7.35906134e-04]),
 'param_metric': masked_array(data=['euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'euclidean', 'euclidean', 'euclidean', 'euclidean',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan',
                    'manhattan', 'manhattan', 'manhattan', 'manhattan'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[3, 3, 5, 5, 7, 7, 9, 9, 11, 11, 13, 13, 3, 3, 5, 5, 7,
                    7, 9, 9, 11, 11, 13, 13],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 9, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 11, 'weights': 'distance'},
  {'metric': 'euclidean', 'n_neighbors': 13, 'weights': 'uniform'},
  {'metric': 'euclidean', 'n_neighbors': 13, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 5, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 7, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 9, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 11, 'weights': 'distance'},
  {'metric': 'manhattan', 'n_neighbors': 13, 'weights': 'uniform'},
  {'metric': 'manhattan', 'n_neighbors': 13, 'weights': 'distance'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.93333333, 0.96666667,
        0.93333333, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 0.96666667]),
 'split1_test_score': array([0.96666667, 0.96666667, 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 1.        , 0.96666667, 1.        , 0.96666667,
        1.        , 1.        , 1.        , 1.        ]),
 'split2_test_score': array([0.93333333, 0.93333333, 0.93333333, 0.9       , 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 1.        , 1.        ,
        0.96666667, 0.96666667, 0.93333333, 0.93333333, 0.9       ,
        0.9       , 0.96666667, 0.9       , 0.93333333, 0.9       ,
        0.96666667, 0.9       , 0.96666667, 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.96666667, 0.96666667,
        0.96666667, 0.96666667, 0.93333333, 0.93333333, 0.96666667,
        0.96666667, 0.93333333, 0.96666667, 0.93333333, 0.96666667,
        0.96666667, 0.96666667, 0.96666667, 0.96666667]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.96666667, 0.96666667, 0.97333333, 0.96666667, 0.98      ,
        0.98      , 0.97333333, 0.97333333, 0.98      , 0.98666667,
        0.97333333, 0.98      , 0.96      , 0.96      , 0.96      ,
        0.96      , 0.97333333, 0.96      , 0.96666667, 0.96      ,
        0.98      , 0.96666667, 0.97333333, 0.96666667]),
 'std_test_score': array([0.02108185, 0.02108185, 0.02494438, 0.03651484, 0.01632993,
        0.01632993, 0.02494438, 0.02494438, 0.02666667, 0.01632993,
        0.02494438, 0.01632993, 0.02494438, 0.02494438, 0.03265986,
        0.03265986, 0.02494438, 0.03265986, 0.02981424, 0.03265986,
        0.01632993, 0.03651484, 0.02494438, 0.03651484]),
 'rank_test_score': array([13, 13,  7, 13,  2,  2,  7,  7,  2,  1,  7,  2, 23, 23, 19, 19,  7,
        19, 13, 19,  2, 13,  7, 13], dtype=int32)}

In [55]:
knn_res = pd.DataFrame(knn_classifer.cv_results_)

In [56]:
knn_res.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_metric,param_n_neighbors,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006687,0.001873,0.014304,0.008524,euclidean,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,13
1,0.004141,0.000810,0.008152,0.006136,euclidean,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,13
2,0.002710,0.000679,0.005375,0.001779,euclidean,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.933333,0.966667,1.0,0.973333,0.024944,7
3,0.004969,0.001874,0.006924,0.003733,euclidean,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667,1.000000,0.900000,0.966667,1.0,0.966667,0.036515,13
4,0.002679,0.000814,0.004050,0.001294,euclidean,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.966667,1.000000,0.966667,0.966667,1.0,0.980000,0.016330,2

In [57]:
knn_res[['param_n_neighbors','param_weights','params','mean_test_score']].sort_values(by='mean_test_score',ascending=False)

,param_n_neighbors,param_weights,params,mean_test_score
9,11,distance,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.986667
5,7,distance,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.980000
8,11,uniform,"{'metric': 'euclidean', 'n_neighbors': 11, 'we...",0.980000
4,7,uniform,"{'metric': 'euclidean', 'n_neighbors': 7, 'wei...",0.980000
20,11,uniform,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.980000
11,13,distance,"{'metric': 'euclidean', 'n_neighbors': 13, 'we...",0.980000
2,5,uniform,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.973333
6,9,uniform,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.973333
16,7,uniform,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.973333
22,13,uniform,"{'metric': 'manhattan', 'n_neighbors': 13, 'we...",0.973333
10,13,uniform,"{'metric': 'euclidean', 'n_neighbors': 13, 'we...",0.973333
7,9,distance,"{'metric': 'euclidean', 'n_neighbors': 9, 'wei...",0.973333
1,3,distance,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667
0,3,uniform,"{'metric': 'euclidean', 'n_neighbors': 3, 'wei...",0.966667
3,5,distance,"{'metric': 'euclidean', 'n_neighbors': 5, 'wei...",0.966667
18,9,uniform,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.966667
21,11,distance,"{'metric': 'manhattan', 'n_neighbors': 11, 'we...",0.966667
23,13,distance,"{'metric': 'manhattan', 'n_neighbors': 13, 'we...",0.966667
14,5,uniform,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.960000
15,5,distance,"{'metric': 'manhattan', 'n_neighbors': 5, 'wei...",0.960000
19,9,distance,"{'metric': 'manhattan', 'n_neighbors': 9, 'wei...",0.960000
17,7,distance,"{'metric': 'manhattan', 'n_neighbors': 7, 'wei...",0.960000
12,3,uniform,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.960000
13,3,distance,"{'metric': 'manhattan', 'n_neighbors': 3, 'wei...",0.960000

In [58]:
from sklearn.model_selection import RandomizedSearchCV

In [59]:
classifier_r = RandomizedSearchCV((model_svc),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)

In [60]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [61]:
results = pd.DataFrame(classifier_r.cv_results_)

In [62]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004733,0.001272,0.003113,0.000745,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,3
1,0.002948,0.000689,0.003391,0.001436,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,2
2,0.009273,0.008678,0.015088,0.015990,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,3
3,0.003190,0.001470,0.002829,0.002423,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [63]:

results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30          rbf         0.960000
1       20       linear         0.966667
2       30       linear         0.960000
3        1       linear         0.980000